"""create tables

Revision ID: 82fa2c2b63a4
Revises: 
Create Date: 2025-10-03 18:59:22.975473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fa2c2b63a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'child_total',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'dependants',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'socstatus_work_fl',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'socstatus_pens_fl',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'fl_presence_fl',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'own_auto',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'personal_income',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clients', 'work_time',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clients', 'credit',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clients', 'term',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'fst_payment',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clients', 'loan_count',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'closed_fl',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('clients', 'agreement_rk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'target',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'clients', 'predictions', ['id_client'], ['id_client'], source_schema='public', referent_schema='public')
    op.alter_column('predictions', 'agreement_rk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predictions', 'prediction',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_foreign_key(None, 'predictions', 'clients', ['id_client'], ['id_client'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', schema='public', type_='foreignkey')
    op.alter_column('predictions', 'prediction',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('predictions', 'agreement_rk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'clients', schema='public', type_='foreignkey')
    op.alter_column('clients', 'target',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'agreement_rk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'closed_fl',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'loan_count',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'fst_payment',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('clients', 'term',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'credit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('clients', 'work_time',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('clients', 'personal_income',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('clients', 'own_auto',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'fl_presence_fl',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'socstatus_pens_fl',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'socstatus_work_fl',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'dependants',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('clients', 'child_total',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
